// OFILINE GAME WORDS DATABASE

export type WordData = {
  word: string;
  category: string;
  related?: string[]; // palavras parecidas ou relacionadas
  hint?: string;
};

export const WORDS: WordData[] = [
  // Animais
  {
    word: "Cachorro",
    category: "Animais",
    related: ["Gato"],
    hint: "Melhor amigo do homem",
  },
  {
    word: "Gato",
    category: "Animais",
    related: ["Cachorro"],
    hint: "Animal doméstico que mia",
  },
  {
    word: "Elefante",
    category: "Animais",
    related: ["Rinoceronte"],
    hint: "Maior mamífero terrestre",
  },
  {
    word: "Leão",
    category: "Animais",
    related: ["Tigre"],
    hint: "Rei da selva",
  },
  {
    word: "Tigre",
    category: "Animais",
    related: ["Leão"],
    hint: "Felino listrado",
  },
  {
    word: "Cavalo",
    category: "Animais",
    related: ["Burro"],
    hint: "Animal de corrida e montaria",
  },
  {
    word: "Burro",
    category: "Animais",
    related: ["Cavalo"],
    hint: "Parecido com cavalo, mas menor",
  },
  {
    word: "Pato",
    category: "Animais",
    related: ["Ganso"],
    hint: "Animal que nada e grasna",
  },
  {
    word: "Ganso",
    category: "Animais",
    related: ["Pato"],
    hint: "Ave que grasna alto",
  },
  {
    word: "Peixe",
    category: "Animais",
    related: ["Tubarão"],
    hint: "Vive na água",
  },
  {
    word: "Tubarão",
    category: "Animais",
    related: ["Peixe"],
    hint: "Grande peixe predador",
  },
  {
    word: "Papagaio",
    category: "Animais",
    related: ["Passarinho"],
    hint: "Ave que repete sons",
  },
  {
    word: "Passarinho",
    category: "Animais",
    related: ["Papagaio"],
    hint: "Pequeno e canta",
  },
  {
    word: "Coelho",
    category: "Animais",
    related: ["Lebre"],
    hint: "Saltitante e fofo",
  },
  {
    word: "Lebre",
    category: "Animais",
    related: ["Coelho"],
    hint: "Corre rápido",
  },
  {
    word: "Cobra",
    category: "Animais",
    related: ["Serpente"],
    hint: "Rasteja e pode ser venenosa",
  },
  {
    word: "Serpente",
    category: "Animais",
    related: ["Cobra"],
    hint: "Rastejante e perigosa",
  },
  {
    word: "Urso",
    category: "Animais",
    related: ["Rinoceronte"],
    hint: "Grande e peludo",
  },
  {
    word: "Rinoceronte",
    category: "Animais",
    related: ["Elefante"],
    hint: "Possui chifre grande",
  },
  {
    word: "Macaco",
    category: "Animais",
    related: ["Gorila"],
    hint: "Ágil e inteligente",
  },

  // Frutas
  {
    word: "Banana",
    category: "Frutas",
    related: ["Maracujá"],
    hint: "Fruta amarela",
  },
  {
    word: "Maçã",
    category: "Frutas",
    related: ["Pera"],
    hint: "Fruta vermelha ou verde",
  },
  {
    word: "Maracujá",
    category: "Frutas",
    related: ["Banana"],
    hint: "Fruta tropical azedinha",
  },
  {
    word: "Laranja",
    category: "Frutas",
    related: ["Tangerina"],
    hint: "Fruta cítrica laranja",
  },
  {
    word: "Tangerina",
    category: "Frutas",
    related: ["Laranja"],
    hint: "Pequena e doce",
  },
  {
    word: "Uva",
    category: "Frutas",
    related: ["Jabuticaba"],
    hint: "Pequena e cresce em cachos",
  },
  {
    word: "Abacaxi",
    category: "Frutas",
    related: ["Coco"],
    hint: "Fruta tropical com casca grossa",
  },
  {
    word: "Coco",
    category: "Frutas",
    related: ["Abacaxi"],
    hint: "Fruta tropical dura por fora",
  },
  {
    word: "Morango",
    category: "Frutas",
    related: ["Framboesa"],
    hint: "Fruta vermelha pequena",
  },
  {
    word: "Framboesa",
    category: "Frutas",
    related: ["Morango"],
    hint: "Parecida com morango",
  },
  {
    word: "Melancia",
    category: "Frutas",
    related: ["Melão"],
    hint: "Grande e doce, vermelha por dentro",
  },
  {
    word: "Melão",
    category: "Frutas",
    related: ["Melancia"],
    hint: "Fruta doce e arredondada",
  },
  {
    word: "Pera",
    category: "Frutas",
    related: ["Maçã"],
    hint: "Fruta doce, formato de gota",
  },
  {
    word: "Kiwi",
    category: "Frutas",
    related: ["Maracujá"],
    hint: "Fruta verde com sementes pretas",
  },
  {
    word: "Ameixa",
    category: "Frutas",
    related: ["Uva"],
    hint: "Fruta pequena e roxa",
  },
  {
    word: "Abacate",
    category: "Frutas",
    related: ["Banana"],
    hint: "Fruta verde cremosa",
  },
  {
    word: "Cajú",
    category: "Frutas",
    related: ["Manga"],
    hint: "Fruta tropical com castanha",
  },
  {
    word: "Manga",
    category: "Frutas",
    related: ["Cajú"],
    hint: "Fruta doce e amarela",
  },
  {
    word: "Limão",
    category: "Frutas",
    related: ["Laranja"],
    hint: "Fruta cítrica azeda",
  },
  {
    word: "Morango Silvestre",
    category: "Frutas",
    related: ["Framboesa"],
    hint: "Pequena e vermelha",
  },

  // Plantas e flores
  {
    word: "Árvore",
    category: "Plantas",
    related: ["Planta"],
    hint: "Possui tronco e folhas",
  },
  {
    word: "Planta",
    category: "Plantas",
    related: ["Árvore"],
    hint: "Pode ser de vaso ou jardim",
  },
  {
    word: "Flor",
    category: "Plantas",
    related: ["Rosa"],
    hint: "Colorida e perfumada",
  },
  {
    word: "Rosa",
    category: "Plantas",
    related: ["Flor"],
    hint: "Flor vermelha ou rosa",
  },
  {
    word: "Girassol",
    category: "Plantas",
    related: ["Tulipa"],
    hint: "Segue o sol",
  },
  {
    word: "Tulipa",
    category: "Plantas",
    related: ["Girassol"],
    hint: "Flor popular na primavera",
  },
  {
    word: "Samambaia",
    category: "Plantas",
    related: ["Palmeira"],
    hint: "Planta ornamental de folhas longas",
  },
  {
    word: "Palmeira",
    category: "Plantas",
    related: ["Samambaia"],
    hint: "Tronco alto e folhas em leque",
  },
  {
    word: "Violeta",
    category: "Plantas",
    related: ["Orquídea"],
    hint: "Pequena flor roxa",
  },
  {
    word: "Orquídea",
    category: "Plantas",
    related: ["Violeta"],
    hint: "Flor exótica",
  },
  {
    word: "Margarida",
    category: "Plantas",
    related: ["Girassol"],
    hint: "Flor branca com centro amarelo",
  },
  {
    word: "Lírio",
    category: "Plantas",
    related: ["Tulipa"],
    hint: "Flor elegante",
  },

  // Natureza
  {
    word: "Mar",
    category: "Natureza",
    related: ["Oceano"],
    hint: "Grande corpo de água salgada",
  },
  {
    word: "Oceano",
    category: "Natureza",
    related: ["Mar"],
    hint: "Enorme extensão de água",
  },
  {
    word: "Rio",
    category: "Natureza",
    related: ["Lago"],
    hint: "Água que corre em um caminho",
  },
  {
    word: "Lago",
    category: "Natureza",
    related: ["Rio"],
    hint: "Água parada em depressão",
  },
  {
    word: "Montanha",
    category: "Natureza",
    related: ["Colina"],
    hint: "Elevação alta de terra",
  },
  {
    word: "Colina",
    category: "Natureza",
    related: ["Montanha"],
    hint: "Pequena elevação de terra",
  },
  {
    word: "Floresta",
    category: "Natureza",
    related: ["Selva"],
    hint: "Muitos árvores juntas",
  },
  {
    word: "Selva",
    category: "Natureza",
    related: ["Floresta"],
    hint: "Densa e tropical",
  },
  {
    word: "Cachoeira",
    category: "Natureza",
    related: ["Rio"],
    hint: "Água caindo de altura",
  },
  {
    word: "Deserto",
    category: "Natureza",
    related: ["Saara"],
    hint: "Árido e sem água",
  },

  // Objetos
  {
    word: "Carro",
    category: "Objetos",
    related: ["Moto"],
    hint: "Veículo com rodas",
  },
  {
    word: "Moto",
    category: "Objetos",
    related: ["Carro"],
    hint: "Veículo de duas rodas",
  },
  {
    word: "Bicicleta",
    category: "Objetos",
    related: ["Patinete"],
    hint: "Movida a pedal",
  },
  {
    word: "Patinete",
    category: "Objetos",
    related: ["Bicicleta"],
    hint: "Pequeno e se empurra com pé",
  },
  {
    word: "Computador",
    category: "Objetos",
    related: ["Notebook"],
    hint: "Máquina eletrônica",
  },
  {
    word: "Notebook",
    category: "Objetos",
    related: ["Computador"],
    hint: "Portátil",
  },
  {
    word: "Livro",
    category: "Objetos",
    related: ["Caderno"],
    hint: "Conjunto de páginas",
  },
  {
    word: "Caderno",
    category: "Objetos",
    related: ["Livro"],
    hint: "Usado para anotar",
  },
  {
    word: "Relógio",
    category: "Objetos",
    related: ["Ampulheta"],
    hint: "Marca o tempo",
  },
  {
    word: "Ampulheta",
    category: "Objetos",
    related: ["Relógio"],
    hint: "Conta o tempo com areia",
  },

  // Comidas (20 palavras)
  {
    word: "Pizza",
    category: "Comida",
    related: ["Lasanha"],
    hint: "Massa com queijo e molho",
  },
  {
    word: "Lasanha",
    category: "Comida",
    related: ["Pizza"],
    hint: "Massa em camadas",
  },
  {
    word: "Arroz",
    category: "Comida",
    related: ["Feijão"],
    hint: "Acompanhamento básico",
  },
  {
    word: "Feijão",
    category: "Comida",
    related: ["Arroz"],
    hint: "Proteína típica brasileira",
  },
  {
    word: "Hambúrguer",
    category: "Comida",
    related: ["Sanduíche"],
    hint: "Carne entre pão",
  },

  // Filmes e séries famosos / desenho animado (20 palavras)
  {
    word: "Harry Potter",
    category: "Filmes e Séries",
    related: ["Hermione"],
    hint: "Menino bruxo",
  },
  {
    word: "Hermione",
    category: "Filmes e Séries",
    related: ["Harry Potter"],
    hint: "Amiga de Harry",
  },
  {
    word: "Vingadores",
    category: "Filmes e Séries",
    related: ["Homem de Ferro"],
    hint: "Super-heróis da Marvel",
  },
  {
    word: "Homem de Ferro",
    category: "Filmes e Séries",
    related: ["Vingadores"],
    hint: "Bilionário com armadura",
  },
  {
    word: "Frozen",
    category: "Filmes e Séries",
    related: ["Elsa"],
    hint: "Filme da Disney",
  },
  {
    word: "Elsa",
    category: "Filmes e Séries",
    related: ["Frozen"],
    hint: "Rainha do gelo",
  },
  {
    word: "Shrek",
    category: "Filmes e Séries",
    related: ["Burro"],
    hint: "O ogro verde",
  },
  {
    word: "Burro",
    category: "Filmes e Séries",
    related: ["Shrek"],
    hint: "Companheiro falante",
  },
  {
    word: "Star Wars",
    category: "Filmes e Séries",
    related: ["Darth Vader"],
    hint: "Guerra nas estrelas",
  },
  {
    word: "Darth Vader",
    category: "Filmes e Séries",
    related: ["Star Wars"],
    hint: "Vilão de capa preta",
  },
  {
    word: "Matrix",
    category: "Filmes e Séries",
    related: ["Neo"],
    hint: "Realidade simulada",
  },
  {
    word: "Neo",
    category: "Filmes e Séries",
    related: ["Matrix"],
    hint: "Escolhido para salvar o mundo",
  },
  {
    word: "Os Simpsons",
    category: "Filmes e Séries",
    related: ["Homer"],
    hint: "Família amarela",
  },
  {
    word: "Homer",
    category: "Filmes e Séries",
    related: ["Os Simpsons"],
    hint: "Pai da família",
  },
  {
    word: "Friends",
    category: "Filmes e Séries",
    related: ["Rachel"],
    hint: "Sitcom famosa",
  },
  {
    word: "Rachel",
    category: "Filmes e Séries",
    related: ["Friends"],
    hint: "Personagem loira",
  },
  {
    word: "Game of Thrones",
    category: "Filmes e Séries",
    related: ["Jon Snow"],
    hint: "Tronos e dragões",
  },
  {
    word: "Jon Snow",
    category: "Filmes e Séries",
    related: ["Game of Thrones"],
    hint: "Guardião da noite",
  },
  {
    word: "Rick and Morty",
    category: "Filmes e Séries",
    related: ["Morty"],
    hint: "Desenho de ficção científica",
  },
  {
    word: "Morty",
    category: "Filmes e Séries",
    related: ["Rick and Morty"],
    hint: "Netinho nervoso",
  },

  // Esportes (times e jogadores) (20 palavras)
  {
    word: "Cristiano Ronaldo",
    category: "Esportes",
    related: ["Messi"],
    hint: "Futebolista português",
  },
  {
    word: "Messi",
    category: "Esportes",
    related: ["Cristiano Ronaldo"],
    hint: "Futebolista argentino",
  },
  {
    word: "Neymar",
    category: "Esportes",
    related: ["Messi"],
    hint: "Atacante brasileiro",
  },
  {
    word: "Pelé",
    category: "Esportes",
    related: ["Zico"],
    hint: "Rei do futebol",
  },
  {
    word: "Zico",
    category: "Esportes",
    related: ["Pelé"],
    hint: "Ídolo brasileiro",
  },
  {
    word: "Flamengo",
    category: "Esportes",
    related: ["Vasco"],
    hint: "Time do Rio de Janeiro",
  },
  {
    word: "Vasco",
    category: "Esportes",
    related: ["Flamengo"],
    hint: "Rival do Flamengo",
  },
  {
    word: "Palmeiras",
    category: "Esportes",
    related: ["Santos"],
    hint: "Time paulista",
  },
  {
    word: "Santos",
    category: "Esportes",
    related: ["Palmeiras"],
    hint: "Time de Pelé",
  },
  {
    word: "Barcelona",
    category: "Esportes",
    related: ["Real Madrid"],
    hint: "Time espanhol famoso",
  },
  {
    word: "Real Madrid",
    category: "Esportes",
    related: ["Barcelona"],
    hint: "Rival histórico do Barça",
  },
  {
    word: "Lakers",
    category: "Esportes",
    related: ["Celtics"],
    hint: "Time da NBA",
  },
  {
    word: "Celtics",
    category: "Esportes",
    related: ["Lakers"],
    hint: "Rival histórico da NBA",
  },
  {
    word: "LeBron James",
    category: "Esportes",
    related: ["Lakers"],
    hint: "Jogador da NBA",
  },
  {
    word: "Marta",
    category: "Esportes",
    related: ["Neymar"],
    hint: "Futebol feminino brasileiro",
  },
  {
    word: "Simone Biles",
    category: "Esportes",
    related: ["Ginástica"],
    hint: "Ginasta americana",
  },
  {
    word: "Usain Bolt",
    category: "Esportes",
    related: ["Atletismo"],
    hint: "Velocista jamaicano",
  },
  {
    word: "Michael Phelps",
    category: "Esportes",
    related: ["Natação"],
    hint: "Nadador olímpico",
  },
  {
    word: "Roger Federer",
    category: "Esportes",
    related: ["Tênis"],
    hint: "Tenista suíço",
  },

  // Famosos da TV e internet (20 palavras)
  {
    word: "Anitta",
    category: "Famosos",
    related: ["Ludmilla"],
    hint: "Cantora brasileira",
  },
  {
    word: "Ludmilla",
    category: "Famosos",
    related: ["Anitta"],
    hint: "Cantora brasileira",
  },
  {
    word: "Whindersson Nunes",
    category: "Famosos",
    related: ["Felipe Neto"],
    hint: "Comediante e youtuber",
  },
  {
    word: "Felipe Neto",
    category: "Famosos",
    related: ["Whindersson Nunes"],
    hint: "Youtuber brasileiro",
  },
  {
    word: "Kim Kardashian",
    category: "Famosos",
    related: ["Kanye West"],
    hint: "Reality Star",
  },
  {
    word: "Kanye West",
    category: "Famosos",
    related: ["Kim Kardashian"],
    hint: "Rapper americano",
  },
  {
    word: "Beyoncé",
    category: "Famosos",
    related: ["Jay-Z"],
    hint: "Cantora americana",
  },
  {
    word: "Jay-Z",
    category: "Famosos",
    related: ["Beyoncé"],
    hint: "Rapper americano",
  },
  {
    word: "Lady Gaga",
    category: "Famosos",
    related: ["Bradley Cooper"],
    hint: "Cantora americana",
  },
  {
    word: "Bradley Cooper",
    category: "Famosos",
    related: ["Lady Gaga"],
    hint: "Ator e cantor",
  },
  {
    word: "Shakira",
    category: "Famosos",
    related: ["Piqué"],
    hint: "Cantora colombiana",
  },
  {
    word: "Piqué",
    category: "Famosos",
    related: ["Shakira"],
    hint: "Jogador de futebol espanhol",
  },
  {
    word: "Chris Hemsworth",
    category: "Famosos",
    related: ["Thor"],
    hint: "Ator australiano",
  },
  {
    word: "Thor",
    category: "Famosos",
    related: ["Chris Hemsworth"],
    hint: "Deus nórdico dos filmes",
  },
  {
    word: "Tom Holland",
    category: "Famosos",
    related: ["Homem-Aranha"],
    hint: "Ator britânico",
  },
  {
    word: "Homem-Aranha",
    category: "Famosos",
    related: ["Tom Holland"],
    hint: "Super-herói da Marvel",
  },
  {
    word: "Will Smith",
    category: "Famosos",
    related: ["Jada Pinkett"],
    hint: "Ator americano",
  },
  {
    word: "Jada Pinkett",
    category: "Famosos",
    related: ["Will Smith"],
    hint: "Atriz americana",
  },
  {
    word: "Adele",
    category: "Famosos",
    related: ["Ed Sheeran"],
    hint: "Cantora britânica",
  },
  {
    word: "Ed Sheeran",
    category: "Famosos",
    related: ["Adele"],
    hint: "Cantor britânico",
  },

  // Emoções e sentimentos (5 palavras)
  {
    word: "Felicidade",
    category: "Emoções",
    related: ["Alegria"],
    hint: "Sentimento positivo",
  },
  {
    word: "Tristeza",
    category: "Emoções",
    related: ["Saudade"],
    hint: "Sentimento negativo",
  },
  {
    word: "Raiva",
    category: "Emoções",
    related: ["Ira"],
    hint: "Sentimento intenso",
  },
  {
    word: "Medo",
    category: "Emoções",
    related: ["Ansiedade"],
    hint: "Sentimento de alerta",
  },
  {
    word: "Amor",
    category: "Emoções",
    related: ["Carinho"],
    hint: "Sentimento de afeto",
  },

  // Lugares famosos (20 palavras)
  {
    word: "Cristo Redentor",
    category: "Lugares",
    related: ["Pão de Açúcar"],
    hint: "Rio de Janeiro",
  },
  {
    word: "Pão de Açúcar",
    category: "Lugares",
    related: ["Cristo Redentor"],
    hint: "Rio de Janeiro",
  },
  {
    word: "Torre Eiffel",
    category: "Lugares",
    related: ["Louvre"],
    hint: "Paris",
  },
  {
    word: "Louvre",
    category: "Lugares",
    related: ["Torre Eiffel"],
    hint: "Museu em Paris",
  },
  {
    word: "Estátua da Liberdade",
    category: "Lugares",
    related: ["Nova York"],
    hint: "EUA",
  },
  {
    word: "Nova York",
    category: "Lugares",
    related: ["Estátua da Liberdade"],
    hint: "Cidade famosa americana",
  },
  {
    word: "Machu Picchu",
    category: "Lugares",
    related: ["Peru"],
    hint: "Cidade Inca",
  },
  {
    word: "Peru",
    category: "Lugares",
    related: ["Machu Picchu"],
    hint: "País da América do Sul",
  },
  { word: "Taj Mahal", category: "Lugares", related: ["Índia"], hint: "Índia" },
  {
    word: "Índia",
    category: "Lugares",
    related: ["Taj Mahal"],
    hint: "País asiático",
  },
  {
    word: "Grande Muralha",
    category: "Lugares",
    related: ["China"],
    hint: "China",
  },
  {
    word: "China",
    category: "Lugares",
    related: ["Grande Muralha"],
    hint: "País asiático",
  },
  { word: "Coliseu", category: "Lugares", related: ["Roma"], hint: "Itália" },
  {
    word: "Roma",
    category: "Lugares",
    related: ["Coliseu"],
    hint: "Cidade histórica",
  },
  {
    word: "Pirâmides de Gizé",
    category: "Lugares",
    related: ["Egito"],
    hint: "Antigo Egito",
  },
  {
    word: "Egito",
    category: "Lugares",
    related: ["Pirâmides de Gizé"],
    hint: "País africano",
  },
  {
    word: "Sydney Opera House",
    category: "Lugares",
    related: ["Austrália"],
    hint: "Edifício icônico",
  },
  {
    word: "Austrália",
    category: "Lugares",
    related: ["Sydney Opera House"],
    hint: "País continente",
  },
  {
    word: "Big Ben",
    category: "Lugares",
    related: ["Londres"],
    hint: "Relógio famoso",
  },
  {
    word: "Londres",
    category: "Lugares",
    related: ["Big Ben"],
    hint: "Capital da Inglaterra",
  },

  // Países e cidades famosas (20 palavras)
  {
    word: "Brasil",
    category: "Países e Cidades",
    related: ["Rio de Janeiro"],
    hint: "País da América do Sul",
  },
  {
    word: "Estados Unidos",
    category: "Países e Cidades",
    related: ["Nova York"],
    hint: "País da América do Norte",
  },
  {
    word: "França",
    category: "Países e Cidades",
    related: ["Paris"],
    hint: "País europeu",
  },
  {
    word: "Itália",
    category: "Países e Cidades",
    related: ["Roma"],
    hint: "País europeu",
  },
  {
    word: "Japão",
    category: "Países e Cidades",
    related: ["Tóquio"],
    hint: "País asiático",
  },
  {
    word: "Austrália",
    category: "Países e Cidades",
    related: ["Sydney"],
    hint: "País continente",
  },
  {
    word: "Alemanha",
    category: "Países e Cidades",
    related: ["Berlim"],
    hint: "País europeu",
  },
  {
    word: "Canadá",
    category: "Países e Cidades",
    related: ["Toronto"],
    hint: "País da América do Norte",
  },
  {
    word: "México",
    category: "Países e Cidades",
    related: ["Cidade do México"],
    hint: "País da América Central",
  },
  {
    word: "Argentina",
    category: "Países e Cidades",
    related: ["Buenos Aires"],
    hint: "País sul-americano",
  },
  {
    word: "Portugal",
    category: "Países e Cidades",
    related: ["Lisboa"],
    hint: "País europeu",
  },
  {
    word: "Lisboa",
    category: "Países e Cidades",
    related: ["Portugal"],
    hint: "Capital",
  },
  {
    word: "Barcelona",
    category: "Países e Cidades",
    related: ["Espanha"],
    hint: "Cidade espanhola",
  },
  {
    word: "Espanha",
    category: "Países e Cidades",
    related: ["Barcelona"],
    hint: "País europeu",
  },
  {
    word: "Nova York",
    category: "Países e Cidades",
    related: ["Estados Unidos"],
    hint: "Cidade famosa",
  },
  {
    word: "Tóquio",
    category: "Países e Cidades",
    related: ["Japão"],
    hint: "Cidade japonesa",
  },
  {
    word: "Rio de Janeiro",
    category: "Países e Cidades",
    related: ["Brasil"],
    hint: "Cidade brasileira famosa",
  },
  {
    word: "Buenos Aires",
    category: "Países e Cidades",
    related: ["Argentina"],
    hint: "Cidade argentina",
  },
  {
    word: "Cidade do México",
    category: "Países e Cidades",
    related: ["México"],
    hint: "Capital mexicana",
  },
  {
    word: "Berlim",
    category: "Países e Cidades",
    related: ["Alemanha"],
    hint: "Capital alemã",
  },

  // Video Games (5 palavras)
  {
    word: "Super Mario",
    category: "Video Games",
    related: ["Luigi"],
    hint: "Encanador da Nintendo",
  },
  {
    word: "Luigi",
    category: "Video Games",
    related: ["Super Mario"],
    hint: "Irmão de Mario",
  },
  {
    word: "Zelda",
    category: "Video Games",
    related: ["Link"],
    hint: "Princesa do reino de Hyrule",
  },
  {
    word: "Link",
    category: "Video Games",
    related: ["Zelda"],
    hint: "Herói do reino de Hyrule",
  },
  {
    word: "Pikachu",
    category: "Video Games",
    related: ["Pokémon"],
    hint: "Pokémon elétrico famoso",
  },

  // Marcas famosas (5 palavras)
  {
    word: "Nike",
    category: "Marcas",
    related: ["Adidas"],
    hint: "Marca esportiva americana",
  },
  {
    word: "Adidas",
    category: "Marcas",
    related: ["Nike"],
    hint: "Marca esportiva alemã",
  },
  {
    word: "Apple",
    category: "Marcas",
    related: ["Samsung"],
    hint: "Tecnologia e iPhones",
  },
  {
    word: "Samsung",
    category: "Marcas",
    related: ["Apple"],
    hint: "Tecnologia e celulares",
  },
  {
    word: "Coca-Cola",
    category: "Marcas",
    related: ["Pepsi"],
    hint: "Bebida famosa mundial",
  },

  // Personagens (5 palavras)
  {
    word: "Harry Potter",
    category: "Personagens",
    related: ["Hermione"],
    hint: "Menino bruxo",
  },
  {
    word: "Hermione",
    category: "Personagens",
    related: ["Harry Potter"],
    hint: "Amiga de Harry",
  },
  {
    word: "Batman",
    category: "Personagens",
    related: ["Robin"],
    hint: "Herói de Gotham",
  },
  {
    word: "Robin",
    category: "Personagens",
    related: ["Batman"],
    hint: "Parceiro do Batman",
  },
  {
    word: "Homem-Aranha",
    category: "Personagens",
    related: ["Peter Parker"],
    hint: "Super-herói da Marvel",
  },

  // Músicas e entretenimento (5 palavras)
  {
    word: "Despacito",
    category: "Músicas",
    related: ["Luis Fonsi"],
    hint: "Hit mundial em espanhol",
  },
  {
    word: "Luis Fonsi",
    category: "Músicas",
    related: ["Despacito"],
    hint: "Cantor latino",
  },
  {
    word: "Shape of You",
    category: "Músicas",
    related: ["Ed Sheeran"],
    hint: "Hit internacional",
  },
  {
    word: "Ed Sheeran",
    category: "Músicas",
    related: ["Shape of You"],
    hint: "Cantor britânico",
  },
  {
    word: "Gangnam Style",
    category: "Músicas",
    related: ["PSY"],
    hint: "Hit coreano viral",
  },

  // Jogos (5 palavras)
  {
    word: "Among Us",
    category: "Jogos",
    related: ["Impostor"],
    hint: "Jogo de dedução social",
  },
  {
    word: "Impostor",
    category: "Jogos",
    related: ["Among Us"],
    hint: "Quem sabota o grupo",
  },
  {
    word: "Catan",
    category: "Jogos",
    related: ["Colonizadores"],
    hint: "Jogo de tabuleiro estratégico",
  },
  {
    word: "Colonizadores",
    category: "Jogos",
    related: ["Catan"],
    hint: "Jogo de tabuleiro estratégico",
  },
  {
    word: "Uno",
    category: "Jogos",
    related: ["Cartas"],
    hint: "Jogo de cartas coloridas",
  },
];
